name: Latest blog post workflow
on:
  schedule:
    - cron: '30 18 * * *' # 00:00 IST
    - cron: '30 0 * * *'  # 06:00 IST
    - cron: '30 6 * * *'  # 12:00 IST
    - cron: '30 12 * * *' # 18:00 IST

jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://blog.techcognita.com/feeds/posts/default"
